/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentCoursesCourseIdRouteImport } from './routes/student/courses/$courseId'
import { Route as StudentAssignmentsAssignmentIdRouteImport } from './routes/student/assignments/$assignmentId'
import { Route as StaffCoursesCourseIdRouteImport } from './routes/staff/courses/$courseId'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCoursesCourseIdRoute = StudentCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssignmentsAssignmentIdRoute =
  StudentAssignmentsAssignmentIdRouteImport.update({
    id: '/assignments/$assignmentId',
    path: '/assignments/$assignmentId',
    getParentRoute: () => StudentRoute,
  } as any)
const StaffCoursesCourseIdRoute = StaffCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => StaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/staff': typeof StaffRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/staff/courses/$courseId': typeof StaffCoursesCourseIdRoute
  '/student/assignments/$assignmentId': typeof StudentAssignmentsAssignmentIdRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/staff': typeof StaffRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/staff/courses/$courseId': typeof StaffCoursesCourseIdRoute
  '/student/assignments/$assignmentId': typeof StudentAssignmentsAssignmentIdRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/staff': typeof StaffRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/staff/courses/$courseId': typeof StaffCoursesCourseIdRoute
  '/student/assignments/$assignmentId': typeof StudentAssignmentsAssignmentIdRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/staff'
    | '/student'
    | '/staff/courses/$courseId'
    | '/student/assignments/$assignmentId'
    | '/student/courses/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/staff'
    | '/student'
    | '/staff/courses/$courseId'
    | '/student/assignments/$assignmentId'
    | '/student/courses/$courseId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/staff'
    | '/student'
    | '/staff/courses/$courseId'
    | '/student/assignments/$assignmentId'
    | '/student/courses/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  StaffRoute: typeof StaffRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/courses/$courseId': {
      id: '/student/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/student/courses/$courseId'
      preLoaderRoute: typeof StudentCoursesCourseIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assignments/$assignmentId': {
      id: '/student/assignments/$assignmentId'
      path: '/assignments/$assignmentId'
      fullPath: '/student/assignments/$assignmentId'
      preLoaderRoute: typeof StudentAssignmentsAssignmentIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/staff/courses/$courseId': {
      id: '/staff/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/staff/courses/$courseId'
      preLoaderRoute: typeof StaffCoursesCourseIdRouteImport
      parentRoute: typeof StaffRoute
    }
  }
}

interface StaffRouteChildren {
  StaffCoursesCourseIdRoute: typeof StaffCoursesCourseIdRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffCoursesCourseIdRoute: StaffCoursesCourseIdRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

interface StudentRouteChildren {
  StudentAssignmentsAssignmentIdRoute: typeof StudentAssignmentsAssignmentIdRoute
  StudentCoursesCourseIdRoute: typeof StudentCoursesCourseIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAssignmentsAssignmentIdRoute: StudentAssignmentsAssignmentIdRoute,
  StudentCoursesCourseIdRoute: StudentCoursesCourseIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  StaffRoute: StaffRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
