/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as StaffSettingsRouteImport } from './routes/staff/settings'
import { Route as StaffNotificationsRouteImport } from './routes/staff/notifications'
import { Route as StaffGradingRouteImport } from './routes/staff/grading'
import { Route as StaffAnalyticsRouteImport } from './routes/staff/analytics'
import { Route as StudentSubmissionsSubmissionIdRouteImport } from './routes/student/submissions/$submissionId'
import { Route as StudentCoursesCourseIdRouteImport } from './routes/student/courses/$courseId'
import { Route as StudentAssignmentsAssignmentIdRouteImport } from './routes/student/assignments/$assignmentId'
import { Route as StaffCoursesCourseIdRouteImport } from './routes/staff/courses/$courseId'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffSettingsRoute = StaffSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StaffRoute,
} as any)
const StaffNotificationsRoute = StaffNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StaffRoute,
} as any)
const StaffGradingRoute = StaffGradingRouteImport.update({
  id: '/grading',
  path: '/grading',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAnalyticsRoute = StaffAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => StaffRoute,
} as any)
const StudentSubmissionsSubmissionIdRoute =
  StudentSubmissionsSubmissionIdRouteImport.update({
    id: '/submissions/$submissionId',
    path: '/submissions/$submissionId',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentCoursesCourseIdRoute = StudentCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssignmentsAssignmentIdRoute =
  StudentAssignmentsAssignmentIdRouteImport.update({
    id: '/assignments/$assignmentId',
    path: '/assignments/$assignmentId',
    getParentRoute: () => StudentRoute,
  } as any)
const StaffCoursesCourseIdRoute = StaffCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => StaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/staff': typeof StaffRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/staff/analytics': typeof StaffAnalyticsRoute
  '/staff/grading': typeof StaffGradingRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/staff/': typeof StaffIndexRoute
  '/student/': typeof StudentIndexRoute
  '/staff/courses/$courseId': typeof StaffCoursesCourseIdRoute
  '/student/assignments/$assignmentId': typeof StudentAssignmentsAssignmentIdRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdRoute
  '/student/submissions/$submissionId': typeof StudentSubmissionsSubmissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/staff/analytics': typeof StaffAnalyticsRoute
  '/staff/grading': typeof StaffGradingRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/staff': typeof StaffIndexRoute
  '/student': typeof StudentIndexRoute
  '/staff/courses/$courseId': typeof StaffCoursesCourseIdRoute
  '/student/assignments/$assignmentId': typeof StudentAssignmentsAssignmentIdRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdRoute
  '/student/submissions/$submissionId': typeof StudentSubmissionsSubmissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/staff': typeof StaffRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/staff/analytics': typeof StaffAnalyticsRoute
  '/staff/grading': typeof StaffGradingRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/staff/': typeof StaffIndexRoute
  '/student/': typeof StudentIndexRoute
  '/staff/courses/$courseId': typeof StaffCoursesCourseIdRoute
  '/student/assignments/$assignmentId': typeof StudentAssignmentsAssignmentIdRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdRoute
  '/student/submissions/$submissionId': typeof StudentSubmissionsSubmissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/staff'
    | '/student'
    | '/staff/analytics'
    | '/staff/grading'
    | '/staff/notifications'
    | '/staff/settings'
    | '/staff/'
    | '/student/'
    | '/staff/courses/$courseId'
    | '/student/assignments/$assignmentId'
    | '/student/courses/$courseId'
    | '/student/submissions/$submissionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/staff/analytics'
    | '/staff/grading'
    | '/staff/notifications'
    | '/staff/settings'
    | '/staff'
    | '/student'
    | '/staff/courses/$courseId'
    | '/student/assignments/$assignmentId'
    | '/student/courses/$courseId'
    | '/student/submissions/$submissionId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/staff'
    | '/student'
    | '/staff/analytics'
    | '/staff/grading'
    | '/staff/notifications'
    | '/staff/settings'
    | '/staff/'
    | '/student/'
    | '/staff/courses/$courseId'
    | '/student/assignments/$assignmentId'
    | '/student/courses/$courseId'
    | '/student/submissions/$submissionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  StaffRoute: typeof StaffRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/settings': {
      id: '/staff/settings'
      path: '/settings'
      fullPath: '/staff/settings'
      preLoaderRoute: typeof StaffSettingsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/notifications': {
      id: '/staff/notifications'
      path: '/notifications'
      fullPath: '/staff/notifications'
      preLoaderRoute: typeof StaffNotificationsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/grading': {
      id: '/staff/grading'
      path: '/grading'
      fullPath: '/staff/grading'
      preLoaderRoute: typeof StaffGradingRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/analytics': {
      id: '/staff/analytics'
      path: '/analytics'
      fullPath: '/staff/analytics'
      preLoaderRoute: typeof StaffAnalyticsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/student/submissions/$submissionId': {
      id: '/student/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/student/submissions/$submissionId'
      preLoaderRoute: typeof StudentSubmissionsSubmissionIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses/$courseId': {
      id: '/student/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/student/courses/$courseId'
      preLoaderRoute: typeof StudentCoursesCourseIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assignments/$assignmentId': {
      id: '/student/assignments/$assignmentId'
      path: '/assignments/$assignmentId'
      fullPath: '/student/assignments/$assignmentId'
      preLoaderRoute: typeof StudentAssignmentsAssignmentIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/staff/courses/$courseId': {
      id: '/staff/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/staff/courses/$courseId'
      preLoaderRoute: typeof StaffCoursesCourseIdRouteImport
      parentRoute: typeof StaffRoute
    }
  }
}

interface StaffRouteChildren {
  StaffAnalyticsRoute: typeof StaffAnalyticsRoute
  StaffGradingRoute: typeof StaffGradingRoute
  StaffNotificationsRoute: typeof StaffNotificationsRoute
  StaffSettingsRoute: typeof StaffSettingsRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StaffCoursesCourseIdRoute: typeof StaffCoursesCourseIdRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffAnalyticsRoute: StaffAnalyticsRoute,
  StaffGradingRoute: StaffGradingRoute,
  StaffNotificationsRoute: StaffNotificationsRoute,
  StaffSettingsRoute: StaffSettingsRoute,
  StaffIndexRoute: StaffIndexRoute,
  StaffCoursesCourseIdRoute: StaffCoursesCourseIdRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

interface StudentRouteChildren {
  StudentIndexRoute: typeof StudentIndexRoute
  StudentAssignmentsAssignmentIdRoute: typeof StudentAssignmentsAssignmentIdRoute
  StudentCoursesCourseIdRoute: typeof StudentCoursesCourseIdRoute
  StudentSubmissionsSubmissionIdRoute: typeof StudentSubmissionsSubmissionIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentIndexRoute: StudentIndexRoute,
  StudentAssignmentsAssignmentIdRoute: StudentAssignmentsAssignmentIdRoute,
  StudentCoursesCourseIdRoute: StudentCoursesCourseIdRoute,
  StudentSubmissionsSubmissionIdRoute: StudentSubmissionsSubmissionIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  StaffRoute: StaffRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
